"""Pydantic Schemas for Data Validation and Serialization.

Defines the structure of API requests, responses, and internal data transfer objects.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Schema for GET /health endpoint response."""
    status: str = "ok"


class AskRequest(BaseModel):
    """Schema for POST /ask request body."""
    question: str = Field(..., min_length=1, description="The user question to answer")


class AskResponse(BaseModel):
    """Schema for POST /ask response body."""
    answer: str = Field(..., description="The answer generated by the LLM using retrieved context")
    sources: List[str] = Field(default_factory=list, description="List of source file paths used for the answer")


class RetrievedChunk(BaseModel):
    """Schema representing a chunk retrieved from vector search."""
    content: str
    source: str
    score: Optional[float] = None
